Repository nextcloud/files_versions_s3, pull requests merged in 2025-03, with the labels that each got.

#92 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#54 [stable29] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#53 [stable30] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#69 Add reuse compliance
  .github/CODEOWNERS
  .github/workflows/reuse.yml
  .gitignore
  .nextcloudignore
  .php-cs-fixer.dist.php
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  REUSE.toml
  appinfo/info.xml
  krankerl.toml
  lib/Command/BrokenConfig.php
  lib/Command/ConfigManager.php
  lib/Command/Enable.php
  lib/Command/S3Config.php
  lib/Command/Status.php
  lib/Versions/AbstractS3VersionBackend.php
  lib/Versions/ExternalS3VersionsBackend.php
  lib/Versions/PrimaryS3VersionsBackend.php
  lib/Versions/S3PreviewFile.php
  lib/Versions/S3VersionProvider.php
  psalm.xml
  tests/Command/S3ConfigTest.php
  tests/TestCase.php
  tests/Versions/S3VersionProviderTest.php
  tests/bootstrap.php
  tests/phpunit.xml
  tests/stubs/stub.phpstub
Labels: documentation, 3. to review
